---
aws_vault_install_location: /usr/local/bin/aws-vault
iamspy_install_location: /usr/local/bin/iamspy
iamgraph_install_location: /usr/local/bin/iamgraph
pacu_install_location: /usr/local/bin/pacu
pmapper_install_location: /usr/local/bin/pmapper
prowler_install_location: /usr/local/bin/prowler
scoutsuite_install_location: /usr/local/bin/scout

aws_vault_version: v7.2.0
cloudfox_version: v1.14.2
stratus_red_team_version: v2.16.0

other_python_tools: 
  - {name: enumerate-iam, repo: https://github.com/skybound1/enumerate-iam, script: enumerate-iam.py}
  - {name: pmapper, repo: https://github.com/Fennerr/PMapper, script: pmapper.py}
  # - {name: name, repo: repourl}
  # - {name: name, repo: repourl}
  # - {name: name, repo: repourl}