---
iodine_install_location: /usr/local/bin/iodine

packages:
  - python3
  - python3-pip
  - python3-virtualenv
  - python3-poetry
  - python3-venv
  - python-is-python3
  - build-essential
  - nmap
  - gnupg
  - ca-certificates
  - curl
  - jq
  - libcap2-bin  # capsh