---
kubectl_install_location: /usr/local/bin/kubectl
yq_install_location: /usr/local/bin/yq
amicontained_install_location: /usr/local/bin/amicontained
rbac_lookup_install_location: /usr/local/bin/rbac-lookup
kubectl_who_can_install_location: /usr/local/bin/kubectl-who-can
etcdctl_install_location: /usr/local/bin/etcdctl
auger_install_location: /usr/local/bin/auger
icekube_install_location: /usr/local/bin/icekube
kubehound_install_location: /usr/local/bin/kubehound

kubernetes_apt_packages:
  - ca-certificates
  - gnupg
  - curl
  - jq
  - libcap2-bin  # capsh

kubernetes_docker_images:
  - skybound/net-utils
  - neo4j:4.4
  - registry:2
  - ghcr.io/datadog/kubehound-graph:latest
  - ghcr.io/datadog/kubehound-ui:latest
